#!/home/satyend/.conda/envs/data_analysis/bin/python

import numpy as np 
import re 
import matplotlib
matplotlib.use('Agg')
import matplotlib.cm as cm
import matplotlib.pyplot as plt 
import pandas as pd
import os
import aux 
import time 
import sys 
import multiprocessing 
import itertools
from sklearn.linear_model import LinearRegression 

os.system("taskset -p 0xfffff %d" % os.getpid())
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['NUMEXPR_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'

sys.stdout.flush() 

'''
This code will take in a trajectory file generated by my MonteCarlo engine and 
gives you the flory exponent
'''
''' 
shebang for cluster: #!/usr/licensed/anaconda3/2020.7/bin/python
shebang for homemachine: #!/usr/bin/env python3
'''


import argparse 
parser = argparse.ArgumentParser(description="Read a trajectory file and obtain the flory exponent from that file.")
parser.add_argument('--dump-file', dest='df', metavar='df', action='store', type=str, help='Name of dump file.')
parser.add_argument('--png-name', dest='pn', metavar='imagename', action='store', type=str, help='Name of image.')
args = parser.parse_args() 

divnorm = matplotlib.colors.SymLogNorm (0.001, vmin=-0.2, vmax=0.1)

if __name__ == "__main__":
	start = time.time()
	##################################

	U_list = aux.dir2U ( os.listdir (".") )

	fig = plt.figure   ( figsize=(8,6) )
	ax  = plt.axes() 
	ax.tick_params(direction='in', bottom=True, top=True, left=True, right=True, which='both')
	ax.tick_params(axis='x', labelsize=16)
	ax.tick_params(axis='y', labelsize=16)
	i = 0 

	##################################
	chi_list = [0.1, 0.05, 0.01, 0.005, 0.001, 0, -0.005, -0.01, -0.05, -0.1, -0.2]
	df = pd.read_csv (args.df, sep='|')
	i = 0
	for U in U_list:
		rgba_color = cm.PiYG (divnorm(chi_list[i]))
		nu = df.loc[df["U"] == U]
		ax.errorbar(nu["T"], nu["nu_mean"]/2, yerr=nu["nu_err"]/2, linewidth=1, capsize=2, color=rgba_color, \
		ecolor='k', fmt='none', label='_nolegend_')
		ax.plot(nu["T"], nu["nu_mean"]/2, linewidth=3, marker='o',markersize=10, markeredgecolor='k', \
		label="_nolabel_", linestyle='-', c=rgba_color)
		i += 1
	stop = time.time() 
	
	my_cmap = cm.PiYG
	# ax.axhline (y=0.58, color='b', linestyle='-')
	ax.axhline (y=0.35, color='r', linestyle='--')
	ax.set_xscale('log')
	yticks = np.arange(0.3, 0.9, 0.1) 
	# yticks = np.hstack ((yticks, 0.57))
	# yticks = np.hstack((yticks, 0.33))
	ax.set_yticks ( yticks ) 
	ax.set_ylim   ( 0.2, 0.85 )
	ax.yaxis.set_minor_locator (matplotlib.ticker.AutoMinorLocator())
	plt.savefig   ( args.pn, bbox_inches='tight', dpi=1000)
	
	print ("Run time is {:.2f} seconds.".format(stop-start), flush=True)

