#!/usr/licensed/anaconda3/2020.7/bin/python

import numpy as np 
import re 
import matplotlib.pyplot as plt 
import pandas as pd
import scipy.optimize as s
import aux 

'''
This code will take in a trajectory file generated by my MonteCarlo engine and 
gives you the Flory exponent.
'''

''' 
shebang for cluster: #!/usr/licensed/anaconda3/2020.7/bin/python
shebang for homemachine: #!/usr/bin/env python3
'''

import argparse 
parser = argparse.ArgumentParser(description="Read multiple trajectories and obtain Flory exponents.")
parser.add_argument('-U', metavar='UX', dest='U', action='store', type=str, help='enter identifier of energy surface.')
parser.add_argument('-s', metavar='S', type=int, dest='s', action='store', help='start parsing after this index.', default=100)
parser.add_argument('-T', metavar='T', type=float, dest='T', action='store', help='enter temperature.')

args = parser.parse_args() 

if __name__ == "__main__":
    
    U = args.U 
    dop_list = aux.dir2temp(os.listdir(U)) # [8, 16, 24, 30, 40]
    temperatures = [args.T] # aux.dir2float ( os.listdir( str(U) +"/DOP_"+str(args.dop) ) )
    
    v_list = [] 
    for T in temperatures:
        v = get_flory(U, str(T), dop_list)
        v_list.append ( v ) 

    
    # plot the flory exponents 
    fig = plt.figure() 
    ax  = plt.axes() 
    ax.plot ( temperatures, v_list, '-.' )
    ax.set_ylabel("Flory exponent ($\\nu$)") 
    ax.set_xlabel("Temperature") 
    plt.show() 
    
