#!/usr/licensed/anaconda3/2020.7/bin/python

import numpy as np 
import re 
import matplotlib
matplotlib.use('Agg')
import matplotlib.cm as cm
import matplotlib.pyplot as plt 
import pandas as pd
import os
import aux 
import time 
import sys 
import multiprocessing 
import itertools

os.system("taskset -p 0xfffff %d" % os.getpid())
os.environ['MKL_NUM_THREADS'] = '1'
os.environ['NUMEXPR_NUM_THREADS'] = '1'
os.environ['OMP_NUM_THREADS'] = '1'

sys.stdout.flush() 

'''
This code will take in a trajectory file generated by my MonteCarlo engine and 
give you Radius of Gyration
'''
''' 
shebang for cluster: #!/usr/licensed/anaconda3/2020.7/bin/python
shebang for homemachine: #!/usr/bin/env python3
'''


import argparse 
parser = argparse.ArgumentParser(description="Read a trajectory file and obtain a radius of gyration plot given a degree of polymerization over a range of temperatures and potential energy surfaces.")
parser.add_argument('-dop', metavar='DOP', dest='dop', type=int, action='store', help='enter a degree of polymerization.')
parser.add_argument('-s', metavar='S', type=int, dest='s', action='store', help='start parsing after this move number (not index or line number in file).')
parser.add_argument('--coords', dest='c', metavar='coords.txt', action='store', type=str, help='Name of energy dump file to parse information.')
parser.add_argument('-T', dest='T', metavar='T', action='store', nargs='+', type=float, help='Enter a temperature.')
parser.add_argument('--png-name', dest='pn', metavar='imagename', action='store', type=str, help='Name of image file', default='rg_plot')
args = parser.parse_args()

divnorm = matplotlib.colors.SymLogNorm (0.5, vmin=0, vmax=1)


if __name__ == "__main__":    
    
    def mysorter_f(x):
        new_str = "" 
        for m in x:
            if m.isdigit():
                new_str = new_str+m
        return float(new_str)
    
    start = time.time() 
    ##################################

    U_list = aux.dir2U ( os.listdir (".") )
    # print (U_list)

    PLOT_DICT  = {}
    ERROR_DICT = {}
    dop            = args.dop
    coords_files   = args.c
    starting_index = args.s
    print("T = ", args.T)
    temperatures = [float(elem) for elem in args.T]
    temperatures.sort() 
    ######
    fig = plt.figure( figsize=(8,6) )
    ax  = plt.axes() 
    ax.tick_params(direction='in', bottom=True, top=True, left=True, right=True, which='both')
    ax.tick_params(axis='x', labelsize=16)
    ax.tick_params(axis='y', labelsize=16)
    i = 0 

    rg_max = 0 
    # instantiating pool
    pool1 = multiprocessing.Pool ( processes=50 )# len(num_list)) 
    pool2 = multiprocessing.Pool ( processes=5 )
    
    pool_list = [pool1, pool2]
    
    # f = open("RG_DATA_"+str(dop)+".mc", "w") 
    
    for T in temperatures:
        frac_list = [] 
        print   ( "For T = " + str(T) + ", and N = " + str(dop), flush=True )
        rg_mean = [] 
        rg_std  = [] 
        # Tmax.append ( np.max(temperatures) )
        
        # get num_list for each temperature 
        master_U_list = []
        master_num_list = []
        rg_dict    = {}
        ntraj_dict = {}
        for U in U_list: 
            frac_list.append (aux.get_frac(U+"/geom_and_esurf.txt"))
            # f.write ( "U = " + str(U) + ":\n" )
            num_list = list(np.unique ( aux.dir2nsim ( os.listdir ( str(U) + "/DOP_" + str(dop) + "/" + str(T) ) ) ) )
            master_num_list.extend ( num_list )
            master_U_list.extend ( [U]*len( num_list ) )
            ntraj_dict[U] = len ( num_list )
            rg_dict   [U] = []

        # start multiprocessing... keeping in mind that each node only has 96 cores 
        # start splitting up master_num_list and master_temp_list 
        mU_list_p1 = master_U_list[0:50]
        mU_list_p2 = master_U_list[50:100]
        mU_list_p3 = master_U_list[100:105]
        mU_list    = [mU_list_p1, mU_list_p2, mU_list_p3]
        
        mnum_list_p1  = master_num_list[0:50]
        mnum_list_p2  = master_num_list[50:100]
        mnum_list_p3  = master_num_list[100:105] 
        mnum_list     = [mnum_list_p1, mnum_list_p2, mnum_list_p3]
        
        # it is a shitty dict 
        shitty_dict = {0:0, 1:0, 2:1 }

        for uidx in range(3):
            
            results = pool_list[ shitty_dict[uidx] ] .starmap ( aux.infiltrate_coords_get_rg, zip( mU_list[uidx], itertools.repeat(str(T)),\
                    mnum_list[uidx], itertools.repeat(dop), \
                    itertools.repeat(coords_files), itertools.repeat(starting_index) ) )

            print ("Pool has been closed. This pool has {} threads.".format (len(results) ), flush=True )     

            for k in range(len(mU_list[uidx])):
                rg_dict[mU_list[uidx][k]].append( results[k] )

            mU_list[uidx] = list(np.unique(mU_list[uidx]))
            mU_list[uidx].sort(key=mysorter_f)
            for U in mU_list[uidx]: 
                rg_mean.append( np.mean ( rg_dict[U] ) ) 
                rg_std.append ( np.std  ( rg_dict[U] )/ np.sqrt( 10 ) ) 

        if rg_max < np.max (rg_mean):
            rg_max = np.max(rg_mean) 

        PLOT_DICT [T] = np.asarray(rg_mean)
        ERROR_DICT[T] = np.asarray(rg_std )
    
    pool1.close()
    pool1.join()

    pool2.close()
    pool2.join() 

    colors = cm.coolwarm(np.linspace(0,1,len(temperatures)))
    i = 0
    for T in temperatures:
        print ("values to plot: ", np.asarray(PLOT_DICT[T])/rg_max)
        ax.errorbar ( frac_list, np.asarray( PLOT_DICT[T] )/rg_max, yerr= np.asarray(ERROR_DICT[T])/rg_max, ecolor=colors[i], linewidth=1, capsize=2, fmt='none', label='_nolegend_' )
        ax.plot     ( frac_list, np.asarray( PLOT_DICT[T] )/rg_max, marker='o', markeredgecolor='k', c=colors[i], \
                    linestyle='-', linewidth=2, label='_nolegend_', markersize=10 )
        i = i + 1

    ########################################
    my_cmap = cm.coolwarm
    sm = plt.cm.ScalarMappable ( cmap=my_cmap, norm=plt.Normalize(vmin=-0.1, vmax=0.1) )
    cbar = plt.colorbar(sm, orientation='vertical') 
    cbar.set_ticks ( [] )
    cbar.set_ticklabels( [] ) 
    # cbar.ax.tick_params(labelsize=14)
    # cbar.ax.set_ylabel ("$\chi ^a$", fontsize=18, rotation=270, labelpad=15)
    # ax.set_xscale('log')
    # ax.set_yscale('log')
    # ax.set_xlabel ( "Temperature (reduced)", fontsize=18) 
    # ax.set_ylabel ( "$\\langle R_g^2 \\rangle/ \\langle R_g ^2 \\rangle _{\\mathrm{max}}$", fontsize=18)
    # plt.legend(args.T)
    plt.savefig   (args.pn+".png", dpi=1000)
    ##################################
    
    stop = time.time() 

    print ("Run time for N = " + str(args.dop) + " is {:.2f} seconds.".format(stop-start), flush=True)
